[package]
name = "utah"
version = "0.1.0"
authors = ["pegasos1 <sgrangan01@gmail.com>"]

[dependencies]
ndarray = "*"
ndarray-rand="*"
rand="*"
num = "*"
chrono = "0.2"
error-chain="*"
itertools = "*"
csv = "*"
rustc-serialize = "*"
[[bin]]
name="df"
path='src/main.rs'

[lib]
path='src/lib.rs'
