[package]
name = "dataframe"
version = "0.1.0"
authors = ["pegasos1 <sgrangan01@gmail.com>"]

[dependencies]
ndarray = "*"
ndarray-rand="*"
rand="*"

[[bin]]
name="dataframe"
path='src/main.rs'

[lib]
path='src/lib.rs'
